python3 ./manage.py test datamodel.tests_models.GameModelTests
python3 ./manage.py test datamodel.tests_models.MoveModelTests
python3 ./manage.py test datamodel.tests_models.CounterModelTests
python3 ./manage.py test logic.tests_services.ServiceBaseTest
python3 ./manage.py test logic.tests_services.LogInOutServiceTests
python3 ./manage.py test logic.tests_services.SignupServiceTests 
python3 ./manage.py test logic.tests_services.CounterServiceTests
python3 ./manage.py test logic.tests_services.LogInOutCounterServiceTests
python3 ./manage.py test logic.tests_services.GameRequiredBaseServiceTests
python3 ./manage.py test logic.tests_services.BckGamesServiceTests
python3 ./manage.py test logic.tests_services.CreateGameServiceTests
python3 ./manage.py test logic.tests_services.JoinGameServiceTests 
python3 ./manage.py test logic.tests_services.SelectGameServiceTests
python3 ./manage.py test logic.tests_services.PlayGameBaseServiceTests
python3 ./manage.py test logic.tests_services.PlayServiceTests
python3 ./manage.py test logic.tests_services.MoveServiceTests
python3 ./manage.py test logic.tests_function.GameMoveTests