# Generated by Django 2.1.7 on 2019-11-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20191112_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
