# Generated by Django 2.1.7 on 2019-11-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='counter',
            new_name='value',
        ),
    ]
