# Generated by Django 2.2.6 on 2019-12-12 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_auto_20191119_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
