# Generated by Django 2.2.6 on 2019-12-12 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0005_auto_20191212_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
